package view;

import view.HistoricoView;
import model.Receita;
import model.Despesa;
import dao.DespesaDAO;
import dao.ReceitaDAO;

public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardView
     */
    private int idUsuario;

public DashboardView() {
    initComponents();
}

public DashboardView(int idUsuario) {
    initComponents();
    this.idUsuario = idUsuario;

    menuLateralPanel1.setIdUsuario(idUsuario); 
    
    DespesaDAO despesaDAO = new DespesaDAO();
    ReceitaDAO receitaDAO = new ReceitaDAO();

double despesas = despesaDAO.totalDespesas(idUsuario);
double receitas = receitaDAO.totalReceitas(idUsuario);
double saldo = receitas - despesas;

// coloque nos labels (ajuste nomes)
lblDespesas.setText("R$ " + despesas);
lblReceitas.setText("R$ " + receitas);
lblSaldo.setText("R$ " + saldo);
    
   
}


    private void atualizarResumo() {

    double totalReceitas = 0;
    double totalDespesas = 0;

    for (var r : HistoricoView.listaReceitas) {
        totalReceitas += r.getValor();
    }

    for (var d : HistoricoView.listaDespesas) {
        totalDespesas += d.getValor();
    }

    double saldo = totalReceitas - totalDespesas;

    lblReceitas.setText("Receitas: R$ " + totalReceitas);
    lblDespesas.setText("Despesas: R$ " + totalDespesas);
    lblSaldo.setText("Saldo: R$ " + saldo);
}

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateralPanel1 = new view.MenuLateralPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblReceitas = new javax.swing.JLabel();
        lblDespesas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Dashboard");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSaldo.setText("R$ 0,00");

        lblReceitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReceitas.setText("R$ 0,00");

        lblDespesas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDespesas.setText("R$ 0,00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Saldo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Receitas:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Despesas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLateralPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReceitas)
                            .addComponent(lblSaldo)
                            .addComponent(lblDespesas))))
                .addGap(0, 167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLateralPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaldo)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addComponent(lblReceitas))
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDespesas)
                    .addComponent(jLabel4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDespesas;
    private javax.swing.JLabel lblReceitas;
    private javax.swing.JLabel lblSaldo;
    private view.MenuLateralPanel menuLateralPanel1;
    // End of variables declaration//GEN-END:variables
}
